04_Django/02_DTL/dtl/articles/urls.py
# articles/urls.py

from django.urls import path
from . import views

# 변수명 app_name 꼭 지켜야 함
app_name = 'articles'

urlpatterns = [
    # URL mapping -> include
    # Naming URL patterns
    path('index/', views.index, name='index'),
    # http://127.0.0.1:8000/articles/create/
    path('create/', views.create, name='create'),
    path('<name>/profile/', views.profile, name='profile'),
    path('<int:age>/', views.info, name='info')
]

04_Django/02_DTL/dtl/dtl/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # articles app이 가지고 있는 요청 경로는
    # articles/urls.py 참고해서 처리
    # include('app_name.urls')
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls'))
]

04_Django/02_DTL/dtl/pages/urls.py
from django.urls import path
from . import views

# 변수명 app_name 꼭 지켜야 함
app_name = 'pages'

urlpatterns = [
    # URL mapping -> include
    # Naming URL patterns
    path('index/', views.index, name='index'),
    # http://127.0.0.1:8000/articles/create/
    path('create/', views.create, name='create'),
]

04_Django/02_DTL/dtl/pages/models.py
from django.db import models

# Create your models here.

04_Django/02_DTL/dtl/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')

def create(request):
    return render(request, 'articles/create.html')

def profile(request, name):
    # context 이름은 장고가 기본 구조 짤 때 이렇게 썼었음
    context = {
        # key: value
        'name': name
    }
    return render(request, 'articles/profile.html', context)

def info(request, age):
    context = {
        'age': age
    }
    return render(request, 'articles/info.html', context)

04_Django/02_DTL/dtl/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

def create(request):
    return render(request, 'pages/create.html')

04_Django/02_DTL/dtl/pages/templates/pages/create.html
{% extends 'base.html' %}

{% block title %}
  <h1>게시글 생성 페이지</h1>
{% endblock title %}

{% block content %}
  <form action="">
    <label for="title">글 제목</label> 
    <label for="text" id="title"></label>   
    <br>
    <input type="submit" value="create">
  </form>
{% endblock content %}

04_Django/02_DTL/dtl/pages/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}
  <title>INDEX</title>
{% endblock title %}

{% block content %}
  <h1>INDEX PAGE</h1>
  <a href="{% url 'pages:create' %}"></a>
{% endblock content %}

04_Django/02_DTL/dtl/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BASE</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
  {% comment %} 블럭은 영역별로 제작 가능, 이름 변경 가능{% endcomment %}
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>