04_Django/05_ModelForm/01_crud_live_pjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

04_Django/05_ModelForm/01_crud_live_pjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    # 이미지를 넣지 않아도 게시글이 생성될 수 있도록 하는 조건 두 가지
    # blank=True -> DB에는 '' 빈 문자열 저장 -> 유효성 검사 시 통과 -> 일반적으로 사용
    # null=True -> DB에 NULL 저장 -> 값이 없으므로 문자열 기반 필드에서 사용 피하기
    image = models.ImageField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

04_Django/05_ModelForm/01_crud_live_pjt/articles/forms.py
from django import forms
from .models import Article

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

04_Django/05_ModelForm/01_crud_live_pjt/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        # print(request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()

    context = {'form': form}
    return render(request, 'articles/create.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')


def update(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk=article.pk)
    else:
        form = ArticleForm(instance=article)

    context = {'form': form, 'article': article}
    return render(request, 'articles/update.html', context)

04_Django/05_ModelForm/01_crud_live_pjt/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>글작성</h1>
  <hr>

  <form action="{% url 'articles:create' %}" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
  </form>

{% endblock content %}

04_Django/05_ModelForm/01_crud_live_pjt/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  {% if article.image %}
    <img src="{{article.image.url}}"> 
  {% endif %}

  <p>글 제목 : {{article.title}}</p>
  <p>글 내용 : {{article.content}}</p>
  <p>생성시각 : {{article.created_at}}</p>
  <p>수정시각 : {{article.updated_at}}</p>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="">
  {% endif %}
  <hr>
  <a href="{% url 'articles:index' %}">목록보기</a>
  <a href="{% url 'articles:update' article.pk %}">수정하기</a>
  <form action="{% url 'articles:delete' article.pk %}">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
  </form>
  

{% endblock content %}

04_Django/05_ModelForm/01_crud_live_pjt/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:create' %}">작성하기</a>
  <hr>

  {% for article in articles %}
    <p>글 번호 : {{article.id}}</p>
    <p><a href="{% url 'articles:detail' article.pk %}">글 제목 : {{article.title}}</a></p>
    <p>글 내용 : {{article.content}}</p>
    <hr>
  {% endfor %}

{% endblock content %}