04_Django/04_CRUD/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('index/', views.index, name='index'),
    # variable routing
    path('<int:article_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name="create"),
    # variable routing
    path('edit/<int:article_pk>/', views.edit, name='edit'),
    path('update/<int:article_pk>/', views.update, name='updatel'),
]

04_Django/04_CRUD/articles/models.py
from django.db import models

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField
    # 생성 시간
    created_at = models.DateTimeField(auto_now_add=True)
    # 수정 시간
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'제목 : {self.title}'

04_Django/04_CRUD/articles/views.py
from django.shortcuts import render, redirect
from .models import Articles

def index(request):
    # ORM
    # class.manater.query API
    articles = Articles.objects.all()
    context = {
        # 특정 단어 or 알파벳 영역 선택 후
        # ctrl + d 하면 같은 단어 다 찾아줌
        'articles': articles
    }
    return render(request, 'articles/index.html', context)


def detail(request, article_pk):
    # 특정 게시글 하나 조회
    # 함수 실행 -> article_pk와 pk 값이 동일한 게시글 하나 조회
    article = Articles.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # 게시글 생성 요청에 대한 응답
    # 게시글 생성 해주면 역할 끝
    # 진짜 게시글만 만들어주면 UX 문제
    # 게시글 생성 후 특정 페이지를 사용자 반환하도록
    # 다른 요청 경로로 이동

    # 게시글 생성
    article = Articles()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save

    # 다른 요청 경로로 이동
    return redirect('articles:detail', article.pk)

def edit(request, article_pk):
    # class.manage.query API
    article = Articles.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Articles.objects.get(pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()

    return redirect('articles:detail', article.pk)

def delete(request, article_pk):
    article = Articles.objects.get(pk=article_pk)
    article.delete
    return redirect('articles:index')

04_Django/04_CRUD/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL PAGE</h1>
  <p>제목 | {{ article.title }}</p>
  <p>내용 | {{ article.content }}</p>
  <p>작성 | {{ article.created_at }}</p>
  <p>수정 | {{ article.updated_at }}</p>

  <a href="{% url 'article:edit' article.pk %}">[EDIT]</a>
  <form action="{% url 'article:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="delete">
  </form>
{% endblock content %}

04_Django/04_CRUD/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>수정</h1>
  <form action="{% url 'article:update' article.pk %}" method="POST">
    <!-- 암호 -->
    {% csrf_token %}
     <!-- 제목 -->
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title" value=" {{ article.title }}">
    <br>
    <!-- 내용 -->
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}
    </textarea>
    
    <!-- 버튼 -->
    <input type="submit" value="게시글 수정">

  </form>

{% endblock content %}

04_Django/04_CRUD/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX PAGE</h1>
  <a href="{% url 'article:new' %}">
    [NEW]
  </a>
  {% for article in articles %}
    <p>{{ article.pk }}번 게시글</p>
    {% comment %}
    html 요소 구분은 공백 사용
    {% endcomment %}
    <a href="{% url 'articles:detail' article.pk %}">
      <p>제목 : {{ article.title }}</p>
    </a>
    <hr>
  {% endfor %}
{% endblock content %}

04_Django/04_CRUD/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW PAGE</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {% comment %} 제목 {% endcomment %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title">

    {% comment %} 내용 {% endcomment %}
    <label for="content">내용 : </label>
    <input type="text" id="content" cols="30" rows="10" >

    {% comment %} 제출 {% endcomment %}
    <input type="submit" value="게시글 작성">
  </form>
{% endblock content %}